### ISSUE TITLE
Authentication Failed: Could not obtain access token

### ISSUE THREAD

**Issue by goelprateek** [kakawait/uaa-behind-zuul-sample#25]
Hi @kakawait ,

I have gone through your code. It is working as expected when I clone your repository and deploy them in a docker container.

Using spring-boot 1.5.7.RELEASE

I want to achieve a similar thing. I have few doubts. 

1) when I hit http://localhost:8080/resource  on my ZUUL gateway.
    -- it sends redirect_uri   as redirect_uri=http://localhost:8080/login.
2) I have made some changes in Authorization server for fetching user/client authentication from mongodb datastore. 

grant_type=password/client_credentials are working good. 
But as far as form login is concerned passes up to authorization grant approval screen. but when I approve it shows me white label error showing 

"Authentication failed could not obtain access token".

and forward me to URL "http://localhost:8080/login" 

which means that it is asking for /login resource from zuul gateway. which is not available in zuul gateway. 

I tried to debug the cause but not able to crack it. I hereby attach my debug logs. Can u please help me out.

debug logs from zuul gateway.

[gateway.txt](https://github.com/kakawait/uaa-behind-zuul-sample/files/1321417/gateway.txt)

**Comment by kakawait** [comment]
Firstly I never tried using latest Spring boot version `1.5.7` I have to check if basic sample with update still working. I have to limit scope :)

**Comment by kakawait** [comment]
@goelprateek Just tested and confirmed sample does not work anymore using `Spring boot 1.5.7` and `Spring cloud Dalston.SR3`

I will checkout why. I think your problem is same you may had upgraded to `Spring cloud Dalston.SR3` to be able to work with `Spring boot 1.5.7`

**Comment by goelprateek** [comment]
Hi @kakawait

I got that problem solved just 1 hour before, the problem was in my resource-server I have given context path in the application.yml file as a 

server:
   context-path:/resource .

in zuul routing, i have configured as 

zuul:
  routes:
    resource-server:
      path: /resource/**
    uaa-server:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
  add-proxy-headers: true

as when callback came after hitting authorization server with (code and state) is not forwarded by zuul proxy to proper resource-server address that why ribbon timeout problem occurred that's why my resource-server was never called.  

Many Thanks for such a quick reply.

**Comment by kakawait** [comment]
@goelprateek which version of `Spring cloud` are you using? Because I still got an issue with the sample

**Comment by goelprateek** [comment]
@kakawait  spring cloud version 

> Dalston.SR3
