### ISSUE TITLE
Authentication Failed: Could not obtain access token

### ISSUE THREAD

**Issue by isis-github** [kakawait/uaa-behind-zuul-sample#27]
Hi @kakawait ,

I have gone through your code. It is working as expected when I run it locally.

Using spring-boot 1.5.7.RELEASE

I want to achieve a similar thing.

- Uaa Service is stateless,so it can scale out.
-ApiGateway is stateless.then it can scale out too.

So I add spring session and redis surport to Uaa Service and Uaa Server ,there are dependencies as fowlling.

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.session</groupId>
            <artifactId>spring-session-data-redis</artifactId>
        </dependency>

when I run Uaa Service greater than one.I get "Authentication failed could not obtain access token".
"InvalidGrantException: Invalid authorization code: FDHOsW"

debug logs from zuul gateway.
[apigateway.txt.txt](https://github.com/kakawait/uaa-behind-zuul-sample/files/1337336/apigateway.txt.txt)

**Comment by kakawait** [comment]
@isis-github thank you for reporting. Sorry for delay I was really busy.

Do you still have the issue?

Otherwise I will try to check when I have some time

**Comment by isis-github** [comment]
Yes,I understand. the " authorization code " should be store in databases not in memory.
